### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by NitkarshChourasia**
Review it @sach2212

### CODE REVIEW

**Review by NitkarshChourasia — COMMENTED** [review]
All done.

**Comment by sach2212** [comment]
https://github.com/Asabeneh/30-Days-Of-React/blob/master/images/30_days_of_react.jpg

this is react  repro from  scratch and i am starting with this or should i start backend (nodejs).?

@NitkarshChourasia

**Comment by NitkarshChourasia** [comment]
@sach2212 Start anywhere as long as you understand the codes in it, at least to **some** extent.
By the way, the repository you shared looks promising.
Best of luck.
But, do give consistent time to all of this.
Okay?!
Start anywhere, if you feel it. You can do both a little ....little everyday, I guess so. Anyways this is my thought, you do however you seem to like so.

**Comment by sach2212** [comment]
ha bro merko mess lagra he kyuki github sikh hi raha hu  but dhere dhere its making sense @NitkarshChourasia

**Comment by NitkarshChourasia** [comment]
Yes, consistency matters.
Let the knowledge seep in.

**Pull request merged**
