### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by sach2212**
kindly review this code and and let me know the explaination

### CODE REVIEW

**Comment by sach2212** [comment]
kindly review this code and and let me know the explaination @NitkarshChourasia

**Review by NitkarshChourasia — CHANGES_REQUESTED** [review]
The organization of files are wrong.
https://github.com/NitkarshChourasia/fun_py/blob/main/Python/Easy/%5B411%5D%20Stuttering%20Function%20%5BE%5D.py

see, Sachin my code are in the problem file itself.
Please do this way.

Just copy paste the .js folder and start doing in the problem file itself, the solutions.

Also, I will be updating the .js folder with more **VERY HARD** AND **EXPERT** problems.

**Review by NitkarshChourasia — COMMENTED** [review]
Do the necessary.

**Comment by sach2212** [comment]
> The organization of files are wrong. https://github.com/NitkarshChourasia/fun_py/blob/main/Python/Easy/%5B411%5D%20Stuttering%20Function%20%5BE%5D.py
> 
> see, Sachin my code are in the problem file itself. Please do this way.
> 
> Just copy paste the .js folder and start doing in the problem file itself, the solutions.
> 
> Also, I will be updating the .js folder with more **VERY HARD** AND **EXPERT** problems.

the way you have made a file  should i write code in that only  and like updating it where you  have written "your code goes here"?
@NitkarshChourasia

**Comment by NitkarshChourasia** [comment]
Yes, but for javascript.
Just copy the folder of *.js and then, just start writing in it only.

**Review by NitkarshChourasia — COMMENTED** [review]
So, indeed...either I come here custom and then my name will be available locally or ...by collaborator means...hm...maybe..let's see.

**Pull request closed without merging**
