### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by sach2212**
i have  added 2 js code @NitkarshChourasia

### CODE REVIEW

**Comment by sach2212** [comment]
this is the updarted file @NitkarshChourasia

**Review by NitkarshChourasia — COMMENTED** [review]
Nah, this is not how it should be done.
It will be not feasible to manage when solving thousands of programs, suppose.

**Comment by sach2212** [comment]
should i commit it 1 by one in testing? @NitkarshChourasia

**Comment by sach2212** [comment]
once i made a file of a single code and then  pull a request****?
@NitkarshChourasia

**Pull request closed without merging**
